n1 = input('Digite a primeira nota: ')
n1int = int(n1)
n2 = input('Digite a segunda nota: ')
n2int = int(n2)
n3 = input('Digite a terceira nota: ')
n3int = int(n3)
n4 = input('Digite a quarta nota: ')
n4int = int(n4)
media = (n1int + n2int + n3int + n4int) / 4
print('A média aritmética é', media)